package renderer

import (
	"fmt"
	"strings"
)

// ProjectGroupSpec describes the Keycloak groups to provision for one project.
//
// ADR-009 (native-RBAC, Option A): each dada-cloud project IS an org. gitops-agent
// is the single producer of the Keycloak group tree — it renders declarative
// crossplane CRs into the keycloak-config chart and ArgoCD reconciles them. The
// emitted path topology is the contract dada-cloud's groups[] decoder reads:
//
//	/orgs/{slug}                org container        (parent: orgs-container)
//	/orgs/{slug}/{Role}         org-level role       (role-mapped to realm role {Role})
//
// {Role} is the uniform wire role Owner|Admin|Developer|ReadOnly.
type ProjectGroupSpec struct {
	// ProjectSlug is the project's short name (projects.name). It is also the org id
	// (projects.org_id is backfilled to this value) so the org-role cascade resolves.
	ProjectSlug string
	// Members maps username → wire role ("Owner"|"Admin"|"Developer"|"ReadOnly").
	// project_members.role was rewritten to these values in migration 019. On member
	// change, regenerate this file with the new membership set. Nil/empty = structure only.
	Members map[string]string
}

// wireRoles is the uniform role set, in privilege order. Each becomes a role-bearing
// subgroup /orgs/{slug}/{Role} mapped to the same-named realm role (ADR-009 §2).
var wireRoles = []string{"Owner", "Admin", "Developer", "ReadOnly"}

// realmRoleRef maps a wire role to the crossplane Role CR name defined in the
// keycloak-config chart (iam-realm-roles.yaml). The group Roles CR references the
// realm role by this resource name, so the subgroup grants the role (and, via the
// client-scope mapping, the scopes).
var realmRoleRef = map[string]string{
	"Owner":     "iam-role-owner",
	"Admin":     "iam-role-admin",
	"Developer": "iam-role-developer",
	"ReadOnly":  "iam-role-readonly",
}

// RenderProjectGroups renders a single YAML document containing, for one project/org:
//   - One parent Group CR for /orgs/<slug>
//   - Four role subgroup CRs (/orgs/<slug>/{Owner,Admin,Developer,ReadOnly})
//   - Four group Roles CRs mapping each subgroup to its realm role
//   - One Memberships CR per role that has at least one member
//
// These CRs are committed to the keycloak-config chart's templates/ directory.
// ArgoCD syncs them; provider-keycloak creates/reconciles the groups in Keycloak.
func RenderProjectGroups(spec ProjectGroupSpec) (string, error) {
	if spec.ProjectSlug == "" {
		return "", fmt.Errorf("project slug is required")
	}

	var b strings.Builder

	// Org parent group: /orgs/<slug>
	fmt.Fprintf(&b, `# Auto-generated by gitops-agent for org %q (DO NOT EDIT MANUALLY).
# Regenerated on every project create/update and member change.
# Topology: /orgs/<slug>/<Role> — ADR-009 native RBAC (Option A: gitops-agent is the producer).
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: org-%s
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    name: %s
    parentIdRef:
      name: orgs-container
  providerConfigRef:
    name: keycloak-cluster
`, spec.ProjectSlug, spec.ProjectSlug, spec.ProjectSlug)

	// Role subgroups: /orgs/<slug>/<Role>, each role-mapped to the realm role <Role>.
	for _, role := range wireRoles {
		groupName := roleGroupCRName(spec.ProjectSlug, role)
		fmt.Fprintf(&b, `---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: %s
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    name: %s
    parentIdRef:
      name: org-%s
  providerConfigRef:
    name: keycloak-cluster
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: %s-roles
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    groupIdRef:
      name: %s
    exhaustive: false
    roleIdsRefs:
      - name: %s
  providerConfigRef:
    name: keycloak-cluster
`, groupName, role, spec.ProjectSlug, groupName, groupName, realmRoleRef[role])
	}

	// Memberships CRs — one per role, only if that role has members.
	if len(spec.Members) > 0 {
		roleMembers := map[string][]string{}
		for username, role := range spec.Members {
			roleMembers[role] = append(roleMembers[role], username)
		}
		for _, role := range wireRoles {
			members := roleMembers[role]
			if len(members) == 0 {
				continue
			}
			groupName := roleGroupCRName(spec.ProjectSlug, role)
			fmt.Fprintf(&b, `---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: %s-members
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    groupIdRef:
      name: %s
    members:
`, groupName, groupName)
			for _, m := range members {
				fmt.Fprintf(&b, "      - %s\n", m)
			}
			fmt.Fprintf(&b, "  providerConfigRef:\n    name: keycloak-cluster\n")
		}
	}

	return b.String(), nil
}

// roleGroupCRName is the Group CR name of one role subgroup, /orgs/<slug>/<Role>.
func roleGroupCRName(projectSlug, role string) string {
	return fmt.Sprintf("org-%s-%s", projectSlug, strings.ToLower(role))
}

// ProjectGroupCRNames returns the names of every Group CR RenderProjectGroups
// emits for one project: the org parent plus one subgroup per wire role, in
// parent-first order.
//
// Teardown reads this. The rendered CRs carry deletionPolicy: Orphan, so simply
// dropping the YAML (and letting ArgoCD prune the CRs) leaves the real Keycloak
// groups behind forever — measured 2026-08-10 on project client-a, whose five
// groups were still Ready weeks after the project was gone. DeleteProject flips
// deletionPolicy to Delete on these live CRs first, so the prune reaches through
// the Crossplane provider into Keycloak. Roles and Memberships CRs are not
// listed: their external state lives inside the group, which the group delete
// takes with it.
func ProjectGroupCRNames(projectSlug string) []string {
	names := make([]string, 0, len(wireRoles)+1)
	names = append(names, fmt.Sprintf("org-%s", projectSlug))
	for _, role := range wireRoles {
		names = append(names, roleGroupCRName(projectSlug, role))
	}
	return names
}

// ProjectGroupsGitPath returns the path in the argo-infra state repo where the
// generated org groups YAML is committed. It lives inside the keycloak-config
// chart's templates/ directory so ArgoCD picks it up automatically.
func ProjectGroupsGitPath(projectSlug string) string {
	return fmt.Sprintf(
		"clusters/beget-prod/projects/platform/environments/prod/apps/keycloak-config/chart/templates/org-groups-%s.yaml",
		projectSlug,
	)
}
