package renderer

import (
	"fmt"
	"strings"
)

// ProjectGroupSpec describes the Keycloak groups to provision for one project.
type ProjectGroupSpec struct {
	// ProjectSlug is the project's short name (projects.name, used as the KC group name).
	ProjectSlug string
	// Members maps username → role for the initial membership set.
	// On member change, regenerate this file with the new membership set.
	// Nil/empty = no memberships written (group structure only).
	Members map[string]string // username → role ("developer"|"client-admin"|"client-viewer")
}

// validRoles is the allowed role values for /projects/<slug>/<role> subgroups.
var validRoles = []string{"developer", "client-admin", "client-viewer", "platform-admin"}

// RenderProjectGroups renders a single YAML document containing:
//   - One parent Group CR for /projects/<slug>
//   - Four role subgroup CRs (developer, client-admin, client-viewer, platform-admin)
//   - One Memberships CR per role that has at least one member
//
// These CRs are committed to the keycloak-config chart's templates/ directory.
// ArgoCD syncs them; provider-keycloak creates/reconciles the groups in Keycloak.
func RenderProjectGroups(spec ProjectGroupSpec) (string, error) {
	if spec.ProjectSlug == "" {
		return "", fmt.Errorf("project slug is required")
	}

	var b strings.Builder

	// Parent group: /projects/<slug>
	fmt.Fprintf(&b, `# Auto-generated by gitops-agent for project %q (DO NOT EDIT MANUALLY).
# Regenerated on every project create/update and member change.
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: project-%s
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    name: %s
    parentIdRef:
      name: projects-container
  providerConfigRef:
    name: keycloak-cluster
`, spec.ProjectSlug, spec.ProjectSlug, spec.ProjectSlug)

	// Role subgroups: /projects/<slug>/<role>
	for _, role := range validRoles {
		crName := fmt.Sprintf("project-%s-%s", spec.ProjectSlug, role)
		fmt.Fprintf(&b, `---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: %s
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    name: %s
    parentIdRef:
      name: project-%s
  providerConfigRef:
    name: keycloak-cluster
`, crName, role, spec.ProjectSlug)
	}

	// Memberships CRs — one per role, only if that role has members.
	if len(spec.Members) > 0 {
		roleMembers := map[string][]string{}
		for username, role := range spec.Members {
			roleMembers[role] = append(roleMembers[role], username)
		}
		for _, role := range validRoles {
			members := roleMembers[role]
			if len(members) == 0 {
				continue
			}
			crName := fmt.Sprintf("project-%s-%s-members", spec.ProjectSlug, role)
			groupRef := fmt.Sprintf("project-%s-%s", spec.ProjectSlug, role)
			fmt.Fprintf(&b, `---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: %s
spec:
  deletionPolicy: Orphan
  forProvider:
    realmIdRef:
      name: master
    groupIdRef:
      name: %s
    members:
`, crName, groupRef)
			for _, m := range members {
				fmt.Fprintf(&b, "      - %s\n", m)
			}
			fmt.Fprintf(&b, "  providerConfigRef:\n    name: keycloak-cluster\n")
		}
	}

	return b.String(), nil
}

// ProjectGroupsGitPath returns the path in the argo-infra state repo where the
// generated project groups YAML is committed. It lives inside the keycloak-config
// chart's templates/ directory so ArgoCD picks it up automatically.
func ProjectGroupsGitPath(projectSlug string) string {
	return fmt.Sprintf(
		"clusters/beget-prod/projects/platform/environments/prod/apps/keycloak-config/chart/templates/project-groups-%s.yaml",
		projectSlug,
	)
}
