FROM alpine:3.19
RUN printf '%s\n' \
      https://mirror.yandex.ru/mirrors/alpine/v3.19/main \
      https://mirror.yandex.ru/mirrors/alpine/v3.19/community \
      https://dl-cdn.alpinelinux.org/alpine/v3.19/main \
      https://dl-cdn.alpinelinux.org/alpine/v3.19/community \
      > /etc/apk/repositories \
 && { for i in 1 2 3; do apk add --no-cache ca-certificates && exit 0; sleep 3; done; exit 1; }
WORKDIR /app
COPY bin/tg-gateway ./tg-gateway
EXPOSE 8082
ENTRYPOINT ["./tg-gateway"]
