ALTER TABLE app_health_alerts
    ADD COLUMN IF NOT EXISTS reason TEXT,
    ADD COLUMN IF NOT EXISTS detail TEXT,
    ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

ALTER TABLE app_volume_alerts
    ADD COLUMN IF NOT EXISTS ratio DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
