ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_method TEXT NOT NULL DEFAULT 'card';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS invoice_number TEXT UNIQUE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_inn TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_kpp TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_org_name TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payer_legal_address TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS tbank_operation_id TEXT UNIQUE;

CREATE SEQUENCE IF NOT EXISTS invoice_number_seq;
