package sourcedetect

import (
	"os"
	"testing"
)

// TestDetectClientPackedZip is the cross-language proof for the browser-side
// zip writer (frontend/lib/zip.ts): testdata/client-packed-vite.zip was
// generated by that exact TypeScript code (see the generation invocation
// recorded below), not by Go's archive/zip. If frontend/lib/zip.ts drifts
// from the ZIP format Detect (and, downstream, Go's archive/zip in the real
// unpack path) expects, this is the test that catches it - a passing
// frontend/lib/zip.test.ts only proves the writer agrees with itself.
//
// Regenerate after changing frontend/lib/zip.ts:
//
//	node --experimental-strip-types frontend/lib/gen-fixture.ts
//
// (see frontend/lib/gen-fixture.ts for the exact file set this fixture
// packages: a vite+react my-lovable-app with package.json, src/main.tsx,
// index.html, README.md).
func TestDetectClientPackedZip(t *testing.T) {
	data, err := os.ReadFile("testdata/client-packed-vite.zip")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}

	res, err := Detect(data)
	if err != nil {
		t.Fatalf("Detect: %v", err)
	}
	if res.Format != FormatZip {
		t.Errorf("Format = %q, want zip", res.Format)
	}
	if res.Framework != "vite" {
		t.Errorf("Framework = %q, want vite", res.Framework)
	}
	if res.Port != 5173 {
		t.Errorf("Port = %d, want 5173", res.Port)
	}

	entries, err := listZipEntries(data)
	if err != nil {
		t.Fatalf("listZipEntries: %v", err)
	}
	found := map[string]bool{}
	for _, e := range entries {
		found[e.name] = true
	}
	for _, want := range []string{"my-lovable-app/package.json"} {
		if !found[want] {
			t.Errorf("archive missing candidate entry %q (saw: %v)", want, found)
		}
	}
}
