{{- if and .Values.backend.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-backend
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- with .Values.metrics.prometheusReleaseLabel }}
    release: {{ . }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "dada-cloud-console.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
