{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-gateway
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
  selector:
    {{- include "dada-cloud-console.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
{{- end }}
