{{- if and .Values.portainerAgent.enabled (not .Values.portainerAgent.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-portainer-agent
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.portainerAgent.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
