{{- if and .Values.tgGateway.enabled (not .Values.tgGateway.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dada-cloud-console.fullname" . }}-tg-gateway
  labels:
    {{- include "dada-cloud-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  TG_GATEWAY_DB_URL: {{ .Values.tgGateway.databaseUrl | quote }}
{{- range $key, $value := .Values.tgGateway.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
